nome = str(input("Digite um funcionário: "))
empresa = str(input("Digite a instituição: "))
qtde_funcionarios = int(input("Digite a quantidade de funcionários: "))
mediaMensalidade = float(input("Digite a média da mensalidade: "))
print(nome + " trabalha na empresa " + empresa)
print("Possui:", qtde_funcionarios, "funcionários")
print("A média da mensalidade é de: " + str(mediaMensalidade))
print("=" * 10, "Verifique os tipos de dados abaixo:", "=" * 10)
print("O tipo de dado da variável [nome] é: ", type(nome))
print("O tipo de dado da variável [empresa] é: ", type(empresa))
print("O tipo de dado da variável [qtde_funcionarios] é: ", type(qtde_funcionarios))
print("O tipo de dado da variável [mediaMensalidade] é: ", type(mediaMensalidade))
print("")
responsavel = str(input("Digite o nome do responsável: "))
funcionario = str(input("Digite o nome do funcionário: "))
evento = str(input("Digite o nome do evento: "))
valor = float(input("Digite o valor que será ressarcido: "))
print("Declaro para o senhor " + responsavel + ", que o senhor " + funcionario + " esteve presente no evento " + evento + " e gastou o valor de R$ " + str(valor) + " com a entrada.")
